### ISSUE TITLE
Failed to send_transfer

### ISSUE THREAD

**Issue by ender503** [yillkid/iota-swarm-node#33]
When sending the new claim request to swarm node, it will get the empty reply from server.

To reproduce this error, launch the server and use the following command.

```shell
curl http://localhost:8000 \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{"command":"new_claim","uuid": "SD9BCRDGJYWDHPTDNOPRULFWWG","part_a":"9JVXCXMFAMKLUQQCDACSWJVDLH","part_b":"9JVXCXMFAMKLUQQCDACSWJVDLH","exp_date":"20190101","claim_pic":"https://www.chill.ie/images/Customer-Care/ncb-example.png", "msg":"testing message"}'
curl: (52) Empty reply from server
```

The server-side will print the following error message.
```shell
Exception happened during processing of request from ('1.34.47.14', 54055)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "server.py", line 63, in do_POST
    result = extension_tangleid.load(request_data)
  File "/home/ender503/iota-swarm-node/extensions/tangleid/main.py", line 13, in load
    bundle_hash = new_claim(data)
  File "/home/ender503/iota-swarm-node/extensions/tangleid/main.py", line 52, in new_claim
    response = send_transfer(tag, json.dumps(data), address, 0, dict_tips, debug=0)
  File "/home/ender503/iota-swarm-node/swarm_node.py", line 172, in send_transfer
    return str(obj_txn['hashes'][0])
IndexError: list index out of range
```

**Comment by wusyong** [comment]
The transaction was actually broadcast successfully but failed to find it from the node because it didn't store in iri yet. `dev` branch should already fix this issue:

https://github.com/yillkid/iota-swarm-node/blob/81a82b45d7f269ef3ce43963bb5261e2d4b6041d/swarm_node.py#L150-L151

Moreover, they can be combined as `broadcast_and_store`.

**Comment by jserv** [comment]
@yillkid, You ought to confirm and prepare some test cases accordingly.
