### ISSUE TITLE
Exception happened during processing specific request

### ISSUE THREAD

**Issue by yillkid** [yillkid/iota-swarm-node#4]
Reproduction:

```----------------------------------------
171.34.168.69 - - [22/Jun/2018 12:28:14] "GET http://www.minghui.org/ HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('171.34.168.69', 58976)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by yillkid** [comment]
It's a [python bug](https://bugs.python.org/issue14574) that server response to a broken requester, usually it doesn't turn out to be a problem.
